# Generated by Django 3.1.1 on 2020-10-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='original_bag',
        ),
        migrations.RemoveField(
            model_name='order',
            name='stripe_pid',
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(default='N/A', max_length=40),
            preserve_default=False,
        ),
    ]
